config/routes.rb
Dns::Application.routes.draw do
  get "admin/edit"

  get "admin/create"

  get "admin/update"

  get "admin/destroy"

  get "admin/show"


  resources :admin do
    resources :admin_records do
      get 'disable'
      get 'activate'
      get 'destroy_disabled'
    end
  end

  resources :names do
    resources :records do
      get 'disable'
      get 'activate'
      get 'destroy_disabled'
    end
  end
  #match '/records/new/:zoneid' => 'records#new'
  match '/auth/webmoney/callback', to: 'sessions#create'
  post "auth/webmoney/callback"
  get "sessions/new"
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    get "sign_in", :to => redirect('/users/auth/webmoney'), :as => :new_user_session
    get "login", :to => redirect('/users/auth/webmoney'), :as => :new_session
    get "sign_out", :to => "devise/sessions#destroy"
  end
  root :to => 'names#index'
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/controllers/names_controller.rb
class NamesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :check_admin, :except => [:index, :show]
  #load_and_authorize_resource :class => Record
  def index
    @user = current_user
    @allzones, @alphaParams = Zonename.all.alpha_paginate(params[:letter]){|zone| zone.name}

    @zones = @user.zonenames.order(:name)
    #@allzones = Zonename.where("user_id != ?", @user.id).order(:name).paginate(:page => params[:page])
    ###@allzones = Zonename.order(:name).paginate(:page => params[:page])
  end

  def new
    @user = current_user
  end

  def edit
    @user = current_user
    @zone = @user.zonenames.find(params[:id])
    @records = @zone.ns_records
    @a_records = @zone.a_records
    @soa_record = @zone.soa_record
    @ns_records = @zone.ns_records
    @mx_records = @zone.mx_records
    @aaaa_records = @zone.aaaa_records
    @cname_records = @zone.cname_records
    @ptr_records = @zone.ptr_records
    @txt_records = @zone.txt_records
  end

  def create
    @user = current_user
    @zone = @user.zonenames.create(:name => params[:rec][:name].downcase, :last_edit_user_id => @user.id)
    if @zone.save
      #@user.zonenames << @zone
      @nameserver = Nameserver.find(:all, :order => 'priority')
      #@nameservers = Nameserver.all
      @ns = @nameserver.blank? ? 'ns.molot.ru' : @nameserver.first.name
      @zone.create_soa_record(:zone => params[:rec][:name], :ttl => params[:rec][:ttl], :resp_person => "postmaster@molot.ru", :refresh => '1200', :retry => '3600', :expire => '604800', :minimum => '38400', :host => '@', :data => @ns)
      #@nameservers.each do
      #end
      if @zone.soa_record.save
        flash[:notice] = t('zona.created_successfull')
        redirect_to name_path(@zone)
      else
        @zone.soa_record.errors.each do |attr,message|
          flash[:error] = message
          redirect_to :back and return
        end
      end
    else
      @zone.errors.each do |attr,message|
        flash[:error] = message
      end
      redirect_to :back and return
    end
  end

  def update
    @user = current_user
    @zone = @user.zonenames.find(params[:id])
    @zone.name = params[:rec][:name]
    @soa_record = @zone.soa_record
    @soa_record.ttl = params[:rec][:ttl]
    @records = @zone.records
    @records.each do |z|
      #z.zone = params[:rec][:name]
      #z.save!
    end
    if @zone.save! && @soa_record.save!
      flash[:notice] = t('zona.updated')
      redirect_to name_path @zone
    else
      flash[:error] = t('zona.not_updated')
      redirect_to :back
    end
  end

  def show
    @user = current_user
    @zone = @user.zonenames.find(params[:id])
    @records = @zone.records
    @a_records = @zone.a_records
    @soa_record = @zone.soa_record
    @ns_records = @zone.ns_records
    @mx_records = @zone.mx_records
    @ptr_records = @zone.ptr_records
    @txt_records = @zone.txt_records
    @aaaa_records = @zone.aaaa_records
    @cname_records = @zone.cname_records
    @disabled_records = @zone.disabled_records
  end

  def destroy
    @user = current_user
    @zone = @user.zonenames.find(params[:id])
    if @zone.destroy
      flash[:notice] = t(:record_deleted)
      redirect_to :back
    end
  end
private
  def check_admin
    raise PermissionDenied, "Permission denied" if current_user.roles(:name => 'admin').first.nil?
  end
end

app/helpers/names_helper.rb
module NamesHelper
end

app/views/names/edit.html.haml
%body
  %div.container
    %div.masthead
      %h3.muted DNS Zone editor
      %div.navbar
        %div.navbar-inner
          %div.container
            %ul.nav
              %li.active
                %a{:href => '/'} Home
    %ul.breadcrumb
      %li
        %a{:href => '/'} Home
        %span.divider /
      %li
        %a{:href => name_path}
          =@zone.name
    %div.hero-unit
      %ul{:style=>'list-style:none;'}
        %li
          =t(:zone)
          %b
            =@soa_record.zone
        %li
          TTL:
          %b
            =@soa_record.ttl
        %li
          =t(:default_ns_server)
          %b
            =@soa_record.data
        %li
          =t(:zone_nameservers)
          %b
            -@ns_records.each do |rec|
              =rec.data
      =form_for :rec, :url => {:controller => 'names', :action => 'update'}, :method => 'PUT' do |form|
        =form.label(t(:zone_name))
        =form.text_field(:name, :value => @zone.name)
        =form.label(t(:ttl))
        =form.select :ttl, options_for_select([['3 hours','10800'],['6 hours','21600'],['24 hours','86400'],['3 days','259200']], @soa_record.ttl)
        %p
        =form.button t(:apply), :class => 'btn btn-success'
      =link_to t(:back), :back, :class => 'btn btn-primary'

app/views/names/index.html.haml
%body
  %div.container
    %div.masthead
      %h3.muted DNS Zone editor
      %div.navbar
        %div.navbar-inner
          %div.container
            %ul.nav
              %li.active
                %a{:href => '/'} Home

    %ul.breadcrumb
      %li
        %a{:href => '/'} Home

    %div.hero-unit
      = link_to_function 'Мои записи', 'ToggleMyrecords();'
      %table
        -@zones.each do |x|
          %tr
            %td
              %b
                = link_to x.name, name_path(x)
            %td
              = link_to t(:edit), edit_name_path(x)
            %td
              =link_to t(:remove), name_path(x), :method => 'DELETE', :confirm => "Вы уверены?"
      %hr
      -if !@user.roles(:name => 'admin').blank?
        = link_to_function 'Все записи', 'ToggleAllRecords();'
        = alphabetical_paginate @alphaParams
        %table{:id => "pagination_table"}
          -@allzones.each do |x|
            %tr
              %td
                %b
                  = link_to x.name, admin_path(x)
              %td
                = link_to t(:edit), edit_admin_path(x)
              %td
                =link_to t(:remove), admin_path(x), :method => 'DELETE', :confirm => "Вы уверены?"
        =# will_paginate(@allzones)
    %hr
      %div.pull-right
        =link_to t(:add_zone), new_name_path, :class => 'btn btn-primary', :style => 'padding-botom:10px;'

app/views/names/new.html.haml
%body
  %div.container
    %div.masthead
      %h3.muted DNS Zone editor
      %div.navbar
        %div.navbar-inner
          %div.container
            %ul.nav
              %li.active
                %a{:href => '/'} Home


    %ul.breadcrumb
      %li
        %a{:href => '/'} Home

    %div.hero-unit
      =form_for :rec, :url => {:controller => 'names', :action => 'create'} do |form|
        =form.label(t(:zone_name))
        =form.text_field(:name)
        =form.label(t(:ttl))
        =form.select :ttl, options_for_select([['3 hours','10800'],['6 hours','21600'],['24 hours','86400'],['3 days','259200']])
        %p
        =form.button t(:create), :class => 'btn btn-success'
      =link_to t(:back), :back, :class => 'btn btn-primary'

app/views/names/show.html.haml
%body
  %div.container
    %div.masthead
      %h3.muted DNS Zone editor
      %div.navbar
        %div.navbar-inner
          %div.container
            %ul.nav
              %li.active
                %a{:href => '/'} Home

    %ul.breadcrumb
      %li
        %a{:href => '/'} Home
        %span.divider /
      %li
        %a{:href => name_path}
          =@zone.name

    %div.hero-unit
      %ul{:style=>'list-style:none;'}
        %li
          =t(:zone)
          %b
            =@soa_record.zone

          =link_to image_tag("edit.png"), edit_name_path(@zone), :title => t(:edit), :class => 'red-tooltip', :style => 'padding-left:30px;'
        %li
          TTL:
          %b
            =@soa_record.ttl
        %li
          =t(:default_ns_server)
          %b
            =@soa_record.data
        %li
          =t(:zone_nameservers)
          %b
            -@ns_records.each do |rec|
              =rec.data
        %li
          =t(:change_time)+":"
          %b
            =Time.at(@soa_record.serial.to_i).strftime('%Y-%m-%d %H:%M:%S')
      %h2{:onclick => "$('.table').eq(0).toggle();"}
        =t(:active_records)
      %table.table.table-hover
        %tr
          %th
            =t(:zone_domain_name)
          %th
            =t(:record_type)
          %th
            =t(:zone_host)
          %th
            =t(:mx_priority)
          %th
            =t(:actions)
        -@ns_records.each do |x|
          %tr
            %td
              = x.host
            %td
              = x.record_type
            %td
              = x.data
            %td
              =x.mx_priority
            %td
              =link_to image_tag("disable.png"), name_record_disable_path(@zone,x), :title => t(:disable), :class => 'red-tooltip'
              =#link_to t(:remove),  name_records_path(@zone,x), :method => :delete
              =link_to image_tag("delete.png"),  {:controller => 'records', :action => 'destroy', :name_id => @zone.id, :id => x.id}, :method => :delete, :confirm => "Вы уверены?", :title => t(:remove), :class => 'red-tooltip'
              =link_to image_tag("edit.png"), edit_name_record_path(@zone,x), :title => t(:edit), :class => 'red-tooltip'
        -@mx_records.each do |x|
          %tr
            %td
              = x.host
            %td
              = x.record_type
            %td
              = x.data
            %td
              =x.mx_priority
            %td
              =link_to image_tag("disable.png"), name_record_disable_path(@zone,x), :title => t(:disable), :class => 'red-tooltip'
              =#link_to t(:remove),  name_records_path(@zone,x), :method => :delete
              =link_to image_tag("delete.png"),  {:controller => 'records', :action => 'destroy', :name_id => @zone.id, :id => x.id}, :method => :delete, :confirm => "Вы уверены?", :title => t(:remove), :class => 'red-tooltip'
              =link_to image_tag("edit.png"), edit_name_record_path(@zone,x), :title => t(:edit), :class => 'red-tooltip'
        -if !@ptr_records.nil?
          -@ptr_records.each do |x|
            %tr
              %td
                = x.host
              %td
                = x.record_type
              %td
                = x.data
              %td
                =x.mx_priority
              %td
                =link_to image_tag("disable.png"), name_record_disable_path(@zone,x), :title => t(:disable), :class => 'red-tooltip'
                =#link_to t(:remove),  name_records_path(@zone,x), :method => :delete
                =link_to image_tag("delete.png"),  {:controller => 'records', :action => 'destroy', :name_id => @zone.id, :id => x.id}, :method => :delete, :confirm => "Вы уверены?", :title => t(:remove), :class => 'red-tooltip'
                =link_to image_tag("edit.png"), edit_name_record_path(@zone,x), :title => t(:edit), :class => 'red-tooltip'
        -if !@txt_records.nil?
          -@txt_records.each do |x|
            %tr
              %td
                = x.host
              %td
                = x.record_type
              %td
                = x.data
              %td
                =x.mx_priority
              %td
                =link_to image_tag("disable.png"), name_record_disable_path(@zone,x), :title => t(:disable), :class => 'red-tooltip'
                =#link_to t(:remove),  name_records_path(@zone,x), :method => :delete
                =link_to image_tag("delete.png"),  {:controller => 'records', :action => 'destroy', :name_id => @zone.id, :id => x.id}, :method => :delete, :confirm => "Вы уверены?", :title => t(:remove), :class => 'red-tooltip'
                =link_to image_tag("edit.png"), edit_name_record_path(@zone,x), :title => t(:edit), :class => 'red-tooltip'
        -if !@cname_records.nil?
          -@cname_records.each do |x|
            %tr
              %td
                = x.host
              %td
                = x.record_type
              %td
                = x.data
              %td
                =x.mx_priority
              %td
                =link_to image_tag("disable.png"), name_record_disable_path(@zone,x), :title => t(:disable), :class => 'red-tooltip'
                =#link_to t(:remove),  name_records_path(@zone,x), :method => :delete
                =link_to image_tag("delete.png"),  {:controller => 'records', :action => 'destroy', :name_id => @zone.id, :id => x.id}, :method => :delete, :confirm => "Вы уверены?", :title => t(:remove), :class => 'red-tooltip'
                =link_to image_tag("edit.png"), edit_name_record_path(@zone,x), :title => t(:edit), :class => 'red-tooltip'
        -if !@aaaa_records.nil?
          -@aaaa_records.each do |x|
            %tr
              %td
                = x.host
              %td
                = x.record_type
              %td
                = x.data
              %td
                =x.mx_priority
              %td
                =link_to image_tag("disable.png"), name_record_disable_path(@zone,x), :title => t(:disable), :class => 'red-tooltip'
                =#link_to t(:remove),  name_records_path(@zone,x), :method => :delete
                =link_to image_tag("delete.png"),  {:controller => 'records', :action => 'destroy', :name_id => @zone.id, :id => x.id}, :method => :delete, :confirm => "Вы уверены?", :title => t(:remove), :class => 'red-tooltip'
                =link_to image_tag("edit.png"), edit_name_record_path(@zone,x), :title => t(:edit), :class => 'red-tooltip'
        -@a_records.each do |x|
          %tr
            %td
              = x.host
            %td
              = x.record_type
            %td
              = x.data
            %td
              =x.mx_priority
            %td
              =link_to image_tag("disable.png"), name_record_disable_path(@zone,x), :title => t(:disable), :class => 'red-tooltip'
              =#link_to t(:remove),  name_records_path(@zone,x), :method => :delete
              =link_to image_tag("delete.png"),  {:controller => 'records', :action => 'destroy', :name_id => @zone.id, :id => x.id}, :method => :delete, :confirm => "Вы уверены?", :title => t(:remove), :class => 'red-tooltip'
              =link_to image_tag("edit.png"), edit_name_record_path(@zone,x), :title => t(:edit), :class => 'red-tooltip'
        %hr

      -if @a_records.count.to_i == 0.to_i
        =t(:this_zone_has_no_records)
        =button_to t(:add), new_name_record_path(@zone.id), :method => 'get', :class => 'btn btn-primary', :style => 'margin-left:45%;'
      -else
        =button_to t(:add), new_name_record_path(@zone.id), :method => 'get', :class => 'pull-right btn btn-primary'

        %hr
      %h2{:onclick => "$('.table').eq(1).toggle();"}
        =t(:disabled_records)
      %table.table.table-hover.disabled
        %tr
          %th
            =t(:zone_domain_name)
          %th
            =t(:record_type)
          %th
            =t(:zone_host)
          %th
            =t(:actions)
        -@disabled_records.each do |rec|
          %tr
            %td
              = rec.host
            %td
              = rec.record_type
            %td
              = rec.data
            %td
              =link_to image_tag("activate.png"), name_record_activate_path(@zone,rec), :title => t(:activate), :class => 'red-tooltip'
              =link_to image_tag("delete.png"),  {:controller => 'records', :action => 'destroy', :name_id => @zone.id, :id => rec.id}, :method => :delete, :confirm => "Вы уверены?", :title => t(:remove), :class => 'red-tooltip'
              =link_to image_tag("edit.png"), edit_name_path(rec), :title => t(:edit), :class => 'red-tooltip'